### ISSUE TITLE
Sample script

### ISSUE THREAD

**Issue by parfum3r** [jamesRUS52/tinkoff-invest#1]
Please add a sample script with base functions: get currencies, send order...

**Comment by jamesRUS52** [comment]
There are main functions in README.md f.g. sample for send order is
```php
require_once 'vendor/autoload.php';

use \jamesRUS52\TinkoffInvest\TIClient;
use \jamesRUS52\TinkoffInvest\TISiteEnum;
use \jamesRUS52\TinkoffInvest\TICurrencyEnum;
use \jamesRUS52\TinkoffInvest\TIInstrument;
use \jamesRUS52\TinkoffInvest\TIPortfolio;
use \jamesRUS52\TinkoffInvest\TIOperationEnum;
use \jamesRUS52\TinkoffInvest\TIIntervalEnum;

$client = new TIClient("TOKEN",TISiteEnum::EXCHANGE);

$order = $client->sendOrder("BBG000BVPV84", 1, TIOperationEnum::BUY, 1.2);
print $order->getORderId();
```

**Comment by parfum3r** [comment]
How to get ticker by symbol?

**Comment by parfum3r** [comment]
My code
`<?php
 
require_once 'vendor/autoload.php';

use \jamesRUS52\TinkoffInvest\TIClient;
use \jamesRUS52\TinkoffInvest\TISiteEnum;
use \jamesRUS52\TinkoffInvest\TICurrencyEnum;
use \jamesRUS52\TinkoffInvest\TIInstrument;
use \jamesRUS52\TinkoffInvest\TIPortfolio;
use \jamesRUS52\TinkoffInvest\TIOperationEnum;
use \jamesRUS52\TinkoffInvest\TIIntervalEnum;
use \jamesRUS52\TinkoffInvest\TIException;


$client = new TIClient("t.Jasdfvsdfvsdfvsdfvdfgbdfgbertb",TISiteEnum::EXCHANGE);
$instr = $client->getCurrencies(["USD000UTSTOM"]);
print_r($instr);
echo "<br>";
$port = $client->getPortfolio();
print_r($port);
echo "<br>";
print $port->getCurrencyBalance(TICurrencyEnum::RUB);
echo "<br>";

?>`

shows it

`Array ( [0] => jamesRUS52\TinkoffInvest\TIInstrument Object ( [figi:jamesRUS52\TinkoffInvest\TIInstrument:private] => BBG0013HGFT4 [ticker:jamesRUS52\TinkoffInvest\TIInstrument:private] => USD000UTSTOM [isin:jamesRUS52\TinkoffInvest\TIInstrument:private] => [minPriceIncrement:jamesRUS52\TinkoffInvest\TIInstrument:private] => 0.0025 [lot:jamesRUS52\TinkoffInvest\TIInstrument:private] => 1000 [currency:jamesRUS52\TinkoffInvest\TIInstrument:private] => RUB ) )

Fatal error: Class 'jamesRUS52\TinkoffInvest\Exception' not found in C:\OSPanel\modules\php\PHP-5.6\vendor\james.rus52\tinkoffinvest\src\TIClient.php on line 449`

**Comment by jamesRUS52** [comment]
> How to get ticker by symbol?

Do you mean ticker by company name?
It's not possible in current API version. It's problem for me too. I will send request to API vendor about it.

Now, you can only send order if you already know ticker name

```php
$inst = $client->getInstrumentByTicker("AMZN");
$order = $client->sendOrder($inst->getFigi(), 1, TIOperationEnum::BUY, 10);
print $order->getStatus();
```

**Comment by jamesRUS52** [comment]
> My code
> `<?php
> 
> require_once 'vendor/autoload.php';
> 
> use \jamesRUS52\TinkoffInvest\TIClient;
> use \jamesRUS52\TinkoffInvest\TISiteEnum;
> use \jamesRUS52\TinkoffInvest\TICurrencyEnum;
> use \jamesRUS52\TinkoffInvest\TIInstrument;
> use \jamesRUS52\TinkoffInvest\TIPortfolio;
> use \jamesRUS52\TinkoffInvest\TIOperationEnum;
> use \jamesRUS52\TinkoffInvest\TIIntervalEnum;
> use \jamesRUS52\TinkoffInvest\TIException;
> 
> $client = new TIClient("t.Jasdfvsdfvsdfvsdfvdfgbdfgbertb",TISiteEnum::EXCHANGE);
> $instr = $client->getCurrencies(["USD000UTSTOM"]);
> print_r($instr);
> echo "
> ";
> $port = $client->getPortfolio();
> print_r($port);
> echo "
> ";
> print $port->getCurrencyBalance(TICurrencyEnum::RUB);
> echo "
> ";
> 
> ?>`
> 
> shows it
> 
> `Array ( [0] => jamesRUS52\TinkoffInvest\TIInstrument Object ( [figi:jamesRUS52\TinkoffInvest\TIInstrument:private] => BBG0013HGFT4 [ticker:jamesRUS52\TinkoffInvest\TIInstrument:private] => USD000UTSTOM [isin:jamesRUS52\TinkoffInvest\TIInstrument:private] => [minPriceIncrement:jamesRUS52\TinkoffInvest\TIInstrument:private] => 0.0025 [lot:jamesRUS52\TinkoffInvest\TIInstrument:private] => 1000 [currency:jamesRUS52\TinkoffInvest\TIInstrument:private] => RUB ) )
> 
> Fatal error: Class 'jamesRUS52\TinkoffInvest\Exception' not found in C:\OSPanel\modules\php\PHP-5.6\vendor\james.rus52\tinkoffinvest\src\TIClient.php on line 449`

Thanks for sending errors.
Please try to update to 0.2.1 version via 
```
composer update
```
you may need to change your composer.json (version in require section) for this update

PS Don't post here your TOKEN for TISiteEnum::EXCHANGE for security reasons

**Comment by parfum3r** [comment]
> > My code
> > `<?php
> > require_once 'vendor/autoload.php';
> > use \jamesRUS52\TinkoffInvest\TIClient;
> > use \jamesRUS52\TinkoffInvest\TISiteEnum;
> > use \jamesRUS52\TinkoffInvest\TICurrencyEnum;
> > use \jamesRUS52\TinkoffInvest\TIInstrument;
> > use \jamesRUS52\TinkoffInvest\TIPortfolio;
> > use \jamesRUS52\TinkoffInvest\TIOperationEnum;
> > use \jamesRUS52\TinkoffInvest\TIIntervalEnum;
> > use \jamesRUS52\TinkoffInvest\TIException;
> > $client = new TIClient("xxxxxxxxxxxxxxxxxxxxxxxxxx",TISiteEnum::EXCHANGE);
> > $instr = $client->getCurrencies(["USD000UTSTOM"]);
> > print_r($instr);
> > echo "
> > ";
> > $port = $client->getPortfolio();
> > print_r($port);
> > echo "
> > ";
> > print $port->getCurrencyBalance(TICurrencyEnum::RUB);
> > echo "
> > ";
> > ?>`
> > shows it
> > `Array ( [0] => jamesRUS52\TinkoffInvest\TIInstrument Object ( [figi:jamesRUS52\TinkoffInvest\TIInstrument:private] => BBG0013HGFT4 [ticker:jamesRUS52\TinkoffInvest\TIInstrument:private] => USD000UTSTOM [isin:jamesRUS52\TinkoffInvest\TIInstrument:private] => [minPriceIncrement:jamesRUS52\TinkoffInvest\TIInstrument:private] => 0.0025 [lot:jamesRUS52\TinkoffInvest\TIInstrument:private] => 1000 [currency:jamesRUS52\TinkoffInvest\TIInstrument:private] => RUB ) )
> > Fatal error: Class 'jamesRUS52\TinkoffInvest\Exception' not found in C:\OSPanel\modules\php\PHP-5.6\vendor\james.rus52\tinkoffinvest\src\TIClient.php on line 449`
> 
> Thanks for sending errors.
> Please try to update to 0.2.1 version via
> 
> ```
> composer update
> ```
> 
> you may need to change your composer.json (version in require section) for this update
> 
> PS Don't post here your TOKEN for TISiteEnum::EXCHANGE for security reasons

 Updating james.rus52/tinkoffinvest (0.1 => 0.2.1): Downloading (connecting..Downloading (100%)

now script shows it
 Fatal error: Uncaught exception 'jamesRUS52\TinkoffInvest\TIException' with message 'Error Пользователь не найден' in C:\OSPanel\modules\php\PHP-5.6\vendor\james.rus52\tinkoffinvest\src\TIClient.php:454 Stack trace: #0 C:\OSPanel\modules\php\PHP-5.6\vendor\james.rus52\tinkoffinvest\src\TIClient.php(255): jamesRUS52\TinkoffInvest\TIClient->sendRequest('/portfolio/curr...', 'GET') #1 C:\OSPanel\domains\localhost\tinko.php(19): jamesRUS52\TinkoffInvest\TIClient->getPortfolio() #2 {main} thrown in C:\OSPanel\modules\php\PHP-5.6\vendor\james.rus52\tinkoffinvest\src\TIClient.php on line 454

**Comment by parfum3r** [comment]
> > How to get ticker by symbol?
> 
> Do you mean ticker by company name?
> It's not possible in current API version. It's problem for me too. I will send request to API vendor about it.
> 
> Now, you can only send order if you already know ticker name
> 
> ```
> $inst = $client->getInstrumentByTicker("AMZN");
> $order = $client->sendOrder($inst->getFigi(), 1, TIOperationEnum::BUY, 10);
> print $order->getStatus();
> ```

How to show this:
USDRUB - 64,205

**Comment by jamesRUS52** [comment]
'Error Пользователь не найден'
ok, It's real problem. User not found
I think, if you have real broker account in Tinkoff, your should send request to support
or try to recreate your token

> How to show this:
USDRUB - 64,205

It's look funny, I don't see it in documentation
API is too uncooked now
I will ask in support about it

**Comment by jamesRUS52** [comment]
for User not found error
If your work on SANDBOX try to do this first
```php
$client->sbRegister();
```

**Comment by parfum3r** [comment]
> 'Error Пользователь не найден'
> ok, It's real problem. User not found
> I think, if you have real broker account in Tinkoff, your should send request to support
> or try to recreate your token
> 
> > How to show this:
> > USDRUB - 64,205
> 
> It's look funny, I don't see it in documentation
> API is too uncooked now
> I will ask in support about it

Is there really no symbol price in API?

**Comment by jamesRUS52** [comment]
I am shocked too )

**Comment by jamesRUS52** [comment]
I am awaiting reply from support

**Comment by parfum3r** [comment]
> for User not found error
> If your work on SANDBOX try to do this first
> 
> ```
> $client->sbRegister();
> ```

No, sandbox for baby, only hardcore only real account)))

**Comment by jamesRUS52** [comment]
I have updated README just now
in v0.3
do this
```php
$instr = $client->getInstrumentByTicker("USD000UTSTOM");
        $orderbook = $client->getOrderBook($instr->getFigi());
        print 'Price to Buy: '.$orderbook->getBestPriceToBuy().' Price to Sell: '.$orderbook->getBestPriceToSell()."\n";
```

**Comment by parfum3r** [comment]
> I have updated README just now
> in v0.3
> do this
> 
> ```
> $instr = $client->getInstrumentByTicker("USD000UTSTOM");
> $orderbook = $client->getOrderBook($instr->getFigi());
> print 'Price to Buy: '.$orderbook->getBestPriceToBuy().' Price to Sell: '.$orderbook->getBestPriceToSell()."\n";
> ```

All good, i see prices aaaaand this:
Fatal error: Uncaught exception 'jamesRUS52\TinkoffInvest\TIException' with message 'Error Пользователь не найден' in C:\OSPanel\modules\php\PHP-5.6\vendor\james.rus52\tinkoffinvest\src\TIClient.php:464 Stack trace: #0 C:\OSPanel\modules\php\PHP-5.6\vendor\james.rus52\tinkoffinvest\src\TIClient.php(265): jamesRUS52\TinkoffInvest\TIClient->sendRequest('/portfolio/curr...', 'GET') #1 C:\OSPanel\domains\localhost\tinko.php(22): jamesRUS52\TinkoffInvest\TIClient->getPortfolio() #2 {main} thrown in C:\OSPanel\modules\php\PHP-5.6\vendor\james.rus52\tinkoffinvest\src\TIClient.php on line 464

**Comment by jamesRUS52** [comment]
Пользователь не найден
it's old your error 'User not found'
Did you send request to Tinkoff support about it?

**Comment by parfum3r** [comment]
> Пользователь не найден
> it's old your error 'User not found'
> Did you send request to Tinkoff support about it?

yes, i send request and wait wait wait for response

**Comment by jamesRUS52** [comment]
may be your token not for requested site?
For sandbox and real exchange use two different separate keys.
Or try to recreate your token.
I have no more ideas

**Comment by parfum3r** [comment]
> may be your token not for requested site?
> For sandbox and real exchange use two different separate keys.
> Or try to recreate your token.
> I have no more ideas

waiting for response from support...
