### ISSUE TITLE
Токен от песочницы в .env

### ISSUE THREAD

**Issue by denismosolov** [jamesRUS52/tinkoff-invest#13]
Благодарю за SDK!

Заметил, что токен от песочницы захардкожен в https://github.com/jamesRUS52/tinkoff-invest/blob/master/tests/TIClientTest.php#L36. Если я правильно понимаю, то через год токен заэкспайрится и тесты будут падать. Не знаю, стоит использовать `.env` для этого или не стоит, но я у себя написал вот такой `setUp`:

```
    public function setUp(): void
    {
        $repository = RepositoryBuilder::createWithNoAdapters()
            ->addAdapter(EnvConstAdapter::class)
            ->addWriter(PutenvAdapter::class)
            ->allowList(['SESSION_USER_ID', 'TINKOFF_OPEN_API_SANDBOX'])
            ->make();
        $dotenv = Dotenv::create($repository, __DIR__ . '/../../');
        $dotenv->load();

        $token = $_ENV['TINKOFF_OPEN_API_SANDBOX'] ?? '';
        $this->client = new TIClient($token, TISiteEnum::SANDBOX);
        $this->client->sbRegister();
    }
```
Токен держку в `.env`. Если желаете, могу сделать нечто подобное для SDK и прислать PR. Если считаете, что это лишнее, то просто закройте issue.

**Comment by jamesRUS52** [comment]
Я не против, присылайте
