### ISSUE TITLE
Ошибка при повторном запросе getInstrumentInfo()

### ISSUE THREAD

**Issue by AlexMiKn** [jamesRUS52/tinkoff-invest#15]
Доброго дня! Спасибо за SDK!

Хочу использовать многократное получение данных по инструменту для мониторинга его статуса.

Если сделать вот такой запрос:

	$inst_info = $client->getInstrumentInfo("$Figi");
	$status = $inst_info -> getTrade_status();
	echo $status."\n";
	
	sleep(5);
	
	$inst_info = $client->getInstrumentInfo("$Figi");
	$status = $inst_info -> getTrade_status();
	echo $status."\n";

получаем ошибку

```
<b>Fatal error</b>:  Uncaught jamesRUS52\TinkoffInvest\TIException: Got empty response for InstrumentInfo in C:\xampp\htdocs\Trading\src\TIClient.php:836
Stack trace:
#0 C:\xampp\htdocs\Trading\trade.php(85): jamesRUS52\TinkoffInvest\TIClient-&gt;getInstrumentInfo('BBG004S68507')
#1 {main}
  thrown in <b>C:\xampp\htdocs\Trading\src\TIClient.php</b> on line <b>836</b><br />
```

При этом, если поставить sleep (4) или меньше, то второй (третий, четвертый.... внутри 5-ти секунд) запрос выполняется без ошибки:
```
normal_trading
normal_trading
```

Запрашивать по одному или разным инструментам - роли не играет.

Или после запроса через getInstrumentInfo нужно что-то еще сделать перед повторным запросом?

**Comment by jamesRUS52** [comment]
На сколько помню, Этот метод - обёртка над вебсокетом для единичного получения информации, поэтому могу предложить что рвется tcp через 5 секунд. Если вам надо отслеживать изменение статуса то лучше использовать непосредственно подписку вебсокетов а не опрашивать сервис через интервал

**Comment by AlexMiKn** [comment]
> На сколько помню, Этот метод - обёртка над вебсокетом для единичного получения информации, поэтому могу предложить что рвется tcp через 5 секунд. Если вам надо отслеживать изменение статуса то лучше использовать непосредственно подписку вебсокетов а не опрашивать сервис через интервал

Спасибо за быстрый ответ!

Решил свою задачу через

```
function action($obj)
{
        print "action\n";
        if ($obj instanceof TICandle)
            print "Figi: ".$obj->getFigi()."Time: ".$obj->getTime ()->format('d.m.Y H:i:s')." Volume: ".$obj->getOpen ()."\n";

}

$client->subscribeGettingCandle($figi, TICandleIntervalEnum::MIN1);
$client->subscribeGettingCandle($figi2, TICandleIntervalEnum::MIN1);
$client->startGetting("action",null,null);
```

Мониторится сразу два инструмента, а потом уже в зависимости от тикера - выполняю действие.
