### ISSUE TITLE
Socket

### ISSUE THREAD

**Issue by eleimt** [jamesRUS52/tinkoff-invest#16]
Функционал для работы с socket соединением на примере reactphp возможен?

**Comment by jamesRUS52** [comment]
Не проверял

**Comment by eleimt** [comment]
Было бы здорово иметь такой пример)

**Comment by jamesRUS52** [comment]
Можете описать кейс, что конкретно вы хотите сделать/получить

**Comment by eleimt** [comment]
К примеру рассмотреть пример как подписаться на какой то стакан и выводить его в консоль.

**Comment by jamesRUS52** [comment]
Так в ридми же есть, в конце , startGetting  и вывод через колбэк функцию action

**Comment by eleimt** [comment]
Ага,увидел, спасибо.
Теперь вопрос, он должен отваливаться через 5-10 строк вывода? Ограничение не делал 2-3 параметрами

**Comment by jamesRUS52** [comment]
если tcp не рвется, то не должен
