### ISSUE TITLE
Не могу запустить процедуры из библиотеки

### ISSUE THREAD

**Issue by Drunvalo-E** [jamesRUS52/tinkoff-invest#17]
Доброго времени суток.
Установил библиотеку - как в описании.
TOKEN корректный - проверил в другом SDK на python.
Выполняю:
	$client = new TIClient($my_TOKEN_SB,TISiteEnum::SANDBOX);
	$client->sbRegister();
и получаю ошибки:
PHP Fatal error:  Uncaught jamesRUS52\TinkoffInvest\TIException: Unknown error in D:\Program\wamp\www\fi\vendor\james.rus52\tinkoffinvest\src\TIResponse.php:67
Stack trace:
#0 D:\Program\wamp\www\fi\vendor\james.rus52\tinkoffinvest\src\TIClient.php(682): jamesRUS52\TinkoffInvest\TIResponse->__construct(false, 0)
#1 D:\Program\wamp\www\fi\vendor\james.rus52\tinkoffinvest\src\TIClient.php(130): jamesRUS52\TinkoffInvest\TIClient->sendRequest('/sandbox/regist...', 'POST')
#2 D:\Program\wamp\www\fi\fi.php(24): jamesRUS52\TinkoffInvest\TIClient->sbRegister()
#3 {main}
  thrown in D:\Program\wamp\www\fi\vendor\james.rus52\tinkoffinvest\src\TIResponse.php on line 67
Что может быть не так?

**Comment by jamesRUS52** [comment]
В 1.1.1 добавил полный вывод ошибки по таким неопознанным.
Попробуйте обновиться и посмотреть что выведет на ней

**Comment by jamesRUS52** [comment]
В общем после некоторого дебага, я на нескольких машинах получил такую же ошибку, 
curl говорит SSL certificate problem: self signed certificate in certificate chain
скорее всего это связано с конфигурацией сертификатов или антивирусов (например Касперский может внедрять свой сертификат в запросы https) на конкретной машине (на других не повторяется).

я добавил в клиент два новых метода, для дебага запросов curl и отключения проверки пира ssl

setDebug(true);
setIgnoreSslPeerVerification(true);

**Comment by Drunvalo-E** [comment]
Отключил брандмауер Win10, а также антивирус встроенный в Win (Касперского нет).
Переустановил библиотеку, но таки продолжается:
Warning: curl_error(): supplied resource is not a valid cURL handle resource in D:\Program\wamp\www\fi\vendor\james.rus52\tinkoffinvest\src\TIClient.php on line 714
PHP Fatal error:  Uncaught Exception in D:\Program\wamp\www\fi\vendor\james.rus52\tinkoffinvest\src\TIClient.php:714
Stack trace:
#0 D:\Program\wamp\www\fi\vendor\james.rus52\tinkoffinvest\src\TIClient.php(134): jamesRUS52\TinkoffInvest\TIClient->sendRequest('/sandbox/regist...', 'POST')
#1 D:\Program\wamp\www\fi\fi.php(33): jamesRUS52\TinkoffInvest\TIClient->sbRegister()
#2 {main}
  thrown in D:\Program\wamp\www\fi\vendor\james.rus52\tinkoffinvest\src\TIClient.php on line 714
Есть ли смысл развернуть PHP и проч. на другом компьютере (правда там тоже Win10) для чистоты эксперимента? 
Насчёт запросов https - при подключении SDK на python - таких ошибок же не возникает. К слову запросы по потфелю и балансу работают там на этой же машине. Но мне бы хотелось поработать с ордерами в php (документировано лучше)... А тут даже в песочницу не могу зайти... :-(
Куда копать? Может с переменными окружения что не так?....

**Comment by Drunvalo-E** [comment]
Может прояснит что-то:
	$client = new TIClient($TOKEN,TISiteEnum::EXCHANGE);   //EXCHANGE SANDBOX
	$inst_info = $client->getInstrumentInfo("BBG004730RP0");

PHP Fatal error:  Uncaught WebSocket\ConnectionException: Connection to 'wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws' failed: Server sent invalid upgrade response:
HTTP/1.1 403 Forbidden
Server: nginx
Date: Wed, 10 Mar 2021 09:25:57 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 14
X-Content-Type-Options: nosniff in D:\Program\wamp\www\fi\vendor\james.rus52\websocket\lib\Client.php:149
Stack trace:
#0 D:\Program\wamp\www\fi\vendor\james.rus52\websocket\lib\Base.php(48): WebSocket\Client->connect()
#1 D:\Program\wamp\www\fi\vendor\james.rus52\tinkoffinvest\src\TIClient.php(850): WebSocket\Base->send('{\n             ...')
#2 D:\Program\wamp\www\fi\vendor\james.rus52\tinkoffinvest\src\TIClient.php(866): jamesRUS52\TinkoffInvest\TIClient->instrumentInfoSubscribtion('BBG004730RP0')
#3 D:\Program\wamp\www\fi\fi.php(29): jamesRUS52\TinkoffInvest\TIClient->getInstrumentInfo('BBG004730RP0')
#4 {main}
  thrown in D:\Program\wamp\www\fi\vendor\james.rus52\websocket\lib\Client.php on line 149

**Comment by jamesRUS52** [comment]
ссори, не туда дебаг воткнул, попробуйте 1.2.1
и включите дебаг и отключите ssl как я писал выше
$client = new TIClient($my_TOKEN_SB,TISiteEnum::SANDBOX);
$client->setDebug(true);
$client->setIgnoreSslPeerVerification(true);
$client->sbRegister();



что касается 
$client = new TIClient($TOKEN,TISiteEnum::EXCHANGE); //EXCHANGE SANDBOX
$inst_info = $client->getInstrumentInfo("BBG004730RP0");

PHP Fatal error: Uncaught WebSocket\ConnectionException: Connection to 'wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws' failed: Server sent invalid upgrade response:
HTTP/1.1 403 Forbidden

наверно забыли токен поменять на реальный (они разные для песочницы и биржы)

**Comment by Drunvalo-E** [comment]
1. Для песочницы/реальной площадки включение 
   $client->setIgnoreSslPeerVerification(true); 
помогло. Ошибки исчезли.
2. HTTP/1.1 403 Forbidden - да, токен не забыл поменять, но он был не корректен, так что устранил, это на моей стороне было.
Спасибо за поправки, продолжу изучать библиотеку.
