### ISSUE TITLE
Incorrect exception: Bad candle interval expected from 30 minutes to 1 day [VALIDATION_ERROR]

### ISSUE THREAD

**Issue by AndrewRadchenko** [jamesRUS52/tinkoff-invest#18]
Simple test request returns exception in correct conditions.

```
$from = new \DateTime();
        $from->sub(new \DateInterval("P360D"));
        $to = new \DateTime();
        $candles = $client->getHistoryCandles($boeingFigi, $from, $to, TIIntervalEnum:: MIN30);
```

message:

`[to]: Bad candle interval: from=2020-03-20T16:00:00Z to=2021-03-15T16:00:00Z expected from 30 minutes to 1 day [VALIDATION_ERROR]`

**Comment by metaseller** [comment]
@AndrewRadchenko Hi! You requested 360 days from now (1 hour contains six 10-min candles). It exceeds the API limits for a single query.

Here limits from the official repository:
https://user-images.githubusercontent.com/76098250/102868509-525d1500-444b-11eb-8795-b51a595294e3.png

If you really need such a huge number of 30-min candles, you need to make a lot of queries, adjusting the query intervals. (The only thing is to be careful not to exceed the request per second limit)
