### ISSUE TITLE
Пустые поля в данных orderBook

### ISSUE THREAD

**Issue by Drunvalo-E** [jamesRUS52/tinkoff-invest#19]
Доброго времени суток.
Выполняю запрос следующего содержания на предмет считывания данных по стакану (пределы нужно узнать, лот по указанному инструменту в портфеле имеется):
   $FIGI = 'BBG004730N88';
   $client = new TIClient($TOKEN,TISiteEnum::EXCHANGE);
   $inst_info = $client->getInstrumentInfo( $FIGI );
   $status = $inst_info -> getTrade_status();
   if ($status=="normal_trading")
   {
      $candle = $client->getCandle($FIGI, TICandleIntervalEnum::DAY);
      print "FIGI: ".$FIGI.', Low: '.$candle->getLow(). ' High: '.$candle->getHigh().' Open: '.$candle->getOpen().' Close: '.$candle->getClose();

      $orderbook = $client->getOrderBook($FIGI, 1);
      print "Up: ".$orderbook->getLimitUp().", down: ".$orderbook->getLimitDown()
            .", getClosePrice: ".$orderbook->getClosePrice();
	}
На выходе:
   FIGI: BBG004730N88, Low: 285.28 High: 292.66 Open: 286.05 Close: 292.64
   Up: , down: , getClosePrice:   // -- пусто (??)
Что не так с полями типа: $orderbook->getLimitUp()? Они пусты... Правильно ли вызываю?

**Comment by allexme** [comment]
Эти данные есть, если получать стакан через 
```php
$client->getHistoryOrderBook($FIGI, TICandleIntervalEnum::DAY);
```
