### ISSUE TITLE
Поочередное выполнение операций

### ISSUE THREAD

**Issue by cept73** [jamesRUS52/tinkoff-invest#20]
Если у вас стоит задача продажа 10 акций, то каждый запрос будет выполняться поочередно (т.к. curl_exec).
В реальности это может быть весьма не правильно.

**Comment by cept73** [comment]
Спустя 2 месяца. Какие-нибудь новости?

**Comment by jamesRUS52** [comment]
А какие новости вы хотите увидеть? По вашему issue я не вижу ни бага ни доработки, ни предложений. Если вы хотите подать параллельно несколько заявок, думаю можно посмотреть в сторону форка процесса или библиотек типа асинхронного php, я считаю это не задача клиента api

**Comment by cept73** [comment]
Хорошо, пришлю pull request
